name: Python Unit Tests for Task 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install NLTK and Download Resources
      run: |
        pip install nltk
        python -m nltk.downloader vader_lexicon

    - name: Run tests for Task 1
      run: |
        python -m unittest discover -s tests
